### ISSUE TITLE
Failed install

### ISSUE THREAD

**Issue by jjmontgo** [elct9620/heroku-buildpacks-php-with-phalcon#4]
remote: -----> Fetching custom git buildpack... done
remote: -----> PHP with PhalconPHP app detected
remote: -----> Building Enviroment
remote: -----> Downloading pre-compile package: https://github.com/elct9620/heroku-buildpacks-php-with-phalcon/releases/download/0.2.0-alpha/0.2.0-alpha.tar.gz
remote: -----> Updating Config
remote: -----> Setting up Enviroment
remote: -----> Installing Composer Dependencies
remote: /tmp/build_b643fcfa2cc56604bbb873b88a384e2b/php/bin/php: error while loading shared libraries: libjpeg.so.62: cannot open shared object file: No such file or directory
remote: 
remote:  !     Push rejected, failed to compile PHP with PhalconPHP app

**Comment by elct9620** [comment]
Hi, I am busying on my school project. I will check project and fix it as soon as possible.

**Comment by elct9620** [comment]
Due to Heroku release new cedar can use with Docker, I plan to switch this plan to use Docker solution.
It may take some days to do this, but I think it will be more easier to use Heroku with phalcon.

PS. Buildpacks current is hard to build because Heroku stop some tools support, using Docker may be a batter way.

Related News:
https://blog.heroku.com/archives/2015/5/5/introducing_heroku_docker_release_build_deploy_heroku_apps_with_docker

**Comment by gloffreda** [comment]
Any news ?
Completely stuck !

**Comment by elct9620** [comment]
I add [Dockerfile](https://github.com/elct9620/heroku-buildpacks-php-with-phalcon/blob/develop/Dockerfile) for this update, I will update the buildpack soon.

If you need new buildpack now, you can using the `docker` plugin to deploy it.
(But slug is too big, so I decide keep buildpacks, and docker using for create buildpacks pre-compile binary)

**Comment by elct9620** [comment]
I've finished buildpack upgrade.
https://github.com/elct9620/heroku-buildpacks-php-with-phalcon/releases/tag/0.3.0

Now, we have PHP 5.6.9 and Phalcon 2.0.3 and tested on cedar 14.
If still have any problem about install, just reopen this issue or create new one.
