### ISSUE TITLE
Installation AD2018

### ISSUE THREAD

**Issue by Krzysiaczek** [elct9620/heroku-buildpacks-php-with-phalcon#5]
Hi there

I was trying to install this extension on Heroku but no luck. I'm not sure I am so dumb or so much have changed since this was released 3-4 years ago.

In the README you wrote that user-env-compile is required but I could not find info how to install/enable this. Instead I found that was "retired" back in Feb 2014 https://devcenter.heroku.com/changelog-items/416

Here is my build log from Heroku:
```
-----> PHP with PhalconPHP app detected
-----> Building Enviroment
-----> Downloading pre-compile package: https://github.com/elct9620/heroku-buildpacks-php-with-phalcon/releases/download/0.3.0/0.3.0.tar.gz
-----> Updating Config
-----> Setting up Enviroment
-----> Installing Composer Dependencies
/tmp/build_9f280f430d5916ea19cdd464855eebaa/php/bin/php: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
 !     Push rejected, failed to compile PHP with PhalconPHP app.
 !     Push failed
```
I'm not sure if this is important but I've seen some reference in other closed issues, so I'm trying to install this on Heroku-18 EU server if this has any matter.

About other steps, I can't proceed as the build is falling so I can't simply connect to the bash:
```
$ heroku run bash
Running bash on ⬢ crabb-connector... !
 ▸    Cannot run one-off process at this time. Please try again later.
```

If this procedure would work I guess it would allow running Phalcon only on the server side, right? I'd like to run it locally as well. You mentioned somewhere a Docker version but I didn't get such far yet. Would it be OK to set up my own Docker following Phalcon installation and point it to use a local folder (Heroku local app folder) as a source of app files in the container?

**Comment by elct9620** [comment]
Hi,

I think this way is not working for the latest Heroku since Heroku stop some support for buildpacks. I suggest you use the [docker](https://hub.docker.com/r/heroku/cedar/) version to precompile the binary and put into your buildpacks or just customize it using docker.

---

I have written [an article](https://blog.frost.tw/posts/2015/06/16/heroku-cedar-14-docker-customized-environment/) about how to use Docker to setup phalcon environment on Heroku, you can copy and paste the Dockerfile part and try it again.

P.S. I write it in Chinese if you have any problem, you can ask me on this issue.

**Comment by elct9620** [comment]
Oops, I have updated the docker version on this repo but I didn't upgrade it 😓 

I will check it today.

**Comment by elct9620** [comment]
I think I can correctly set up the buildpack, but the environment this project provides is too old. So some shared library didn't exist in the latest Heroku cedar.

```
2018-10-30T10:13:26.252734+00:00 app[web.1]: Launching apache
2018-10-30T10:13:26.317073+00:00 app[web.1]: httpd: Syntax error on line 149 of /app/apache/conf/httpd.conf: Cannot load modules/libphp5.so into server: libpng12.so.0: cannot open shared object file: No such file or directory
2018-10-30T10:13:31.745409+00:00 heroku[web.1]: Starting process with command `sh boot.sh`
2018-10-30T10:13:35.319663+00:00 heroku[web.1]: State changed from starting to crashed
2018-10-30T10:13:35.298182+00:00 heroku[web.1]: Process exited with status 1
2018-10-30T10:13:35.062368+00:00 app[web.1]: Launching apache
2018-10-30T10:13:35.202012+00:00 app[web.1]: httpd: Syntax error on line 149 of /app/apache/conf/httpd.conf: Cannot load modules/libphp5.so into server: libpng12.so.0: cannot open shared object file: No such file or directory
```

**Comment by Krzysiaczek** [comment]
Hi, thanks for a quick answer.
I didn't know I can grab the whole Heroku image and put it locally. 
If I would use it I'd probably go with this version https://hub.docker.com/r/heroku/heroku/ as it supports recent Heroku-18 version.
Still, it only adds confusion cause even if I would manage to install Phalcon on this local instance of Heroku I'm not sure how to transfer this to Heroku remote to run as my application, not mentioning the whole Heroku local CLI communication. Should I switch to talk to my local instance of Heroku or what?
Your article in Chinese is not picked up by Chrome auto translate page (in other languages) so I would have to copy and paste bits by bits to understand anything out of it.

**Comment by Krzysiaczek** [comment]
On top of this Phalcon offers nowadays it's own version of Docker to run locally and I was thinking about this as a way to go hoping that Phalcon could be enabled as other tools (like other components e.g. specific database) with adding somewhere a single line or configuration requirement.

**Comment by elct9620** [comment]
Hi,

This repo is using the very old way to compile the buildpacks. So the readme didn't fit the latest Heroku.

But there is something not change for buildpack. The buildpacks is an archive file includes binary (ex. apache, php, etc ..) and the config file for it.

So, the default Heroku environment use this way to set up. Because it is very fast, and we didn't need compile anything.

In newer Heroku (cedar-14 or newer), we have a docker image can add some customize. So it is possible to pre-compile in local machine and upload to Heroku. (But we have to upload a large file every time)

But I think this way is an easier way to use phalcon on Heroku, because the phalcon already have an official docker image. I think you can follow the [document](https://devcenter.heroku.com/categories/deploying-with-docker) about use docker on Heroku.

**Comment by elct9620** [comment]
This repo is using docker (cedar-14) to precompile binary and archive them upload to GitHub. And I add some config to let it become a buildpacks.

So, this repo is too old that it cannot be used in current cedar-18 runtime.

**Comment by Krzysiaczek** [comment]
It sounds promising as it reminds me of the process of pushing Docker images into Docker Hub. I will give it a try later on but for now, I will switch to some other framework which can be installed on Heroku using simply composer file.

I'm not closing this to motivate you to ideally create a new version or update a readme file at least to mention it's not compatible with newer releases of Heroku (and PHP 7?).

Thanks for the quick response again.
